version: '3'
services:
  api-web-screenshot:
    image: agungsurya/api-web-screenshot:v2
    volumes:
      - /home/agungsurya/screenshoot:/home/agungsurya/screenshoot
    ports:
      - "12002:8000"
    command: python3 -m uvicorn api-screenshoot:app --host=0.0.0.0
